language: android
jdk:
  - oraclejdk8
before_install:
 - chmod +x gradlew
script:
    # Override default ./gradlew build connectedCheck tasks for now until we setup tests correctly
     - ./gradlew build
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - platform-tools
    # - tools

    # The BuildTools version used by your project
    - build-tools-21.1.1

    # The SDK version used to compile your project
    - android-19

    # Additional components
#    - extra-google-m2repository
#    - extra-android-m2repository
#    - addon-google_apis-google-19

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
#    - sys-img-armeabi-v7a-android-19
#    - sys-img-x86-android-17

after_success:
   - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)