language: java
jdk:
  - oraclejdk8
before_install:
 - chmod +x gradlew
script:
    # Override default ./gradlew build connectedCheck tasks for now until we setup tests correctly
     - ./gradlew build
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
after_success:
    - $HOME/.gradle/wrapper/
   - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)